- hosts: all
  become: true
  tasks:
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Load br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: Enable iptables to see bridged traffic
      sysctl: 
        name: "{{ item }}"
        sysctl_file: "/etc/sysctl.d/k8s.conf"
        value: "1"
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        
    - name: Write docker json configs
      copy:
        content: '{ "exec-opts": ["native.cgroupdriver=systemd"] }'
        dest: "/etc/docker/daemon.json"
      
    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh
      notify:
        - docker start
    
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker

    - name: Install requirements
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - curl

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
        
    - name: Install Kubernetes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - kubeadm
        - kubectl
        - kubelet

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.0.10" --apiserver-cert-extra-sans="192.168.0.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Copy kubeconfig to local
      fetch:
        src: /home/vagrant/.kube/config
        dest: kubeconfig
        flat: yes

    - name: Install cilium network plugin
      become: false
      command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/1.7.2/install/kubernetes/quick-install.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./k8s-join.sh"

  handlers:
    - name: docker start
      service:
        name: docker
        state: started