Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define "cluster" do |server|
        server.vm.provider "virtualbox" do |vb|
            vb.name = "cluster"
            vb.memory = 8192
            vb.cpus = 2
        end
        server.vm.host_name = "cluster"
        server.vm.network "public_network", ip: "192.168.0.10"
    end
end
