VM_IMAGE_BOX = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = VM_IMAGE_BOX
        master.vm.host_name = "k8s-master"
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "k8s-master.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
                node_ip: "192.168.50.10",
            }
        end
    end

    config.vm.define "k8s-worker" do |worker|
        worker.vm.box = VM_IMAGE_BOX
        worker.vm.host_name = "k8s-worker"
        worker.vm.network "private_network", ip: "192.168.50.11"
        worker.vm.provision "ansible" do |ansible|
            ansible.playbook = "k8s-worker.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
                node_ip: "192.168.50.11"
            }
        end
    end
end
