apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gateway
spec:
  selectors:
    istio: ingressgateway
  servers:
    - hosts:
        - kibana.life4honor.com 
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - kibana.life4honor.com
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - kibana-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: kibana-kb-http
            port:
              number: 5601
  tls:
    - match:
        - port: 443
          sni_hosts:
            - kibana.life4honor.com
      route:
        - destination:
            host: kibana-kb-http
            port:
              number: 5601
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.5.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: myblk-csi
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.5.2
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  count: 1
  elasticsearchRef:
    name: elasticsearch
